### ISSUE TITLE
OR package is not actually using OR-OpenSSL package

### ISSUE THREAD

**Issue by genavyshel** [openresty/openresty-packaging#10]
Hi.

Beeing able to test OR-packaging scripts i've found that nginx build from openresty.spec is not actually using libs from openresty-openssl package.

> 
> [osboxes@osboxes SPECS]$ ldd /usr/local/openresty/nginx/sbin/nginx 
>    linux-vdso.so.1 (0x00007ffe67dec000)
> 	libdl.so.2 => /lib64/libdl.so.2 (0x00007f4d5a9fe000)
> 	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f4d5a7e1000)
> 	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f4d5a5ab000)
> 	libluajit-5.1.so.2 => /usr/local/openresty/luajit/lib/libluajit-5.1.so.2 (0x00007f4d5a330000)
> 	libm.so.6 => /lib64/libm.so.6 (0x00007f4d5a026000)
> 	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f4d59db3000)
> 	**libssl.so.10 => /lib64/libssl.so.10 (0x00007f4d59b41000)**
> 	**libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f4d596e0000)**
> 	libz.so.1 => /lib64/libz.so.1 (0x00007f4d594ca000)
> 	libc.so.6 => /lib64/libc.so.6 (0x00007f4d59108000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00005563a8e26000)
> 	libfreebl3.so => /lib64/libfreebl3.so (0x00007f4d58f04000)
> 	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f4d58ced000)
> 	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f4d58aa0000)
> 	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f4d587b9000)
> 	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f4d585b5000)
> 	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f4d58384000)
> 	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f4d58174000)
> 	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f4d57f70000)
> 	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f4d57d56000)
> 	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f4d57b2e000)

 
Seems nginx is somehow missing the rpath dependencies. Or am i wrong?
Thanks in advance.

**Comment by agentzh** [comment]
Are you using the official binary rpm packages from our official yum package? What OS are you in?

**Comment by genavyshel** [comment]
I built it using specs from this repo(openresty-packaging) and using instructions from tis repo on Fedora24 kernel 4.8.8

**Comment by agentzh** [comment]
@genavyshel Try the official rpm package in the official yum repo on your side to see if it also has the issue. We generally do not support your own builds of the packages.

**Comment by agentzh** [comment]
@genavyshel See http://openresty.org/en/linux-packages.html for details.

**Comment by agentzh** [comment]
@genavyshel I don't have Fedora 24 myself but the official rpm package openresty looks good on openssl dependencies on my Fedora 23 system:

```
agentzh@fedora64 ~ $ ldd /usr/local/openresty/nginx/sbin/nginx|grep openssl
	libssl.so.1.0.0 => /usr/local/openresty/openssl/lib/libssl.so.1.0.0 (0x00007fd4ca3a5000)
	libcrypto.so.1.0.0 => /usr/local/openresty/openssl/lib/libcrypto.so.1.0.0 (0x00007fd4c9f4e000)
```

**Comment by genavyshel** [comment]
@agentzh thanks for the provided link, i will try. 
But i also want to be able to build OpenResty on my own.
Were the official packages built using specs fom openresty/openresty-packaging repo?

**Comment by agentzh** [comment]
@genavyshel Yes, they were.

**Comment by genavyshel** [comment]
@agentzh is it possible to share your build logs?

**Comment by agentzh** [comment]
They are always publicly available: https://copr.fedorainfracloud.org/coprs/openresty/openresty/builds/

**Comment by agentzh** [comment]
For example, the latest build logs for the `openresty` rpm package built on Fedora 24 x86_64:

https://copr-be.cloud.fedoraproject.org/results/openresty/openresty/fedora-24-x86_64/00481553-openresty/build.log.gz

**Comment by genavyshel** [comment]
@agentzh, Thanks. Looks like problems were caused by outdated rpmdevtools packages. After updating packages with yum and wiping out the contents of rpmbuild folder the problem has gone.

**Comment by agentzh** [comment]
Glad you figured it out. I'm closing this.
