### ISSUE TITLE
Add http_geoip_module support

### ISSUE THREAD

**Issue by pauloschilling** [openresty/openresty-packaging#12]
Hi,

I'm using the RHEL 6 package to install OpenResty on EC2 instances running Amazon Linux, but I figured out that `http_geoip_module` is not included in the package.

There's any chance to add this as a default module, or maybe as a separate package?

Thanks!

**Comment by agentzh** [comment]
@pauloschilling Yeah, we can enable this module by default. Patches welcome :)

**Comment by agentzh** [comment]
@pauloschilling Never mind, I've just committed this change to the git repo. The new version of the `openresty*` packages will appear in the official yum repo shortly. Thanks!

**Comment by pauloschilling** [comment]
Whoa, that was fast!

Thank you so much, @agentzh, this allowed me to finally remove the manual compilation/build script from my provisioning process.

This package works amazingly fine with https://github.com/voxpupuli/puppet-nginx, and all I had to do was just set some extra config params for this Puppet module, since OpenResty has its own service name and paths.

Best!

**Comment by kakaluote444** [comment]
if i want add sticky module to openresty,what should I do for that？（请问下，如果我想添加sticky模块到openresty,我应该怎么做呢？）
