### ISSUE TITLE
question about openresty.init run level

### ISSUE THREAD

**Issue by detailyang** [openresty/openresty-packaging#13]
Hello.

@agentzh I'm confused why we do not set run level in [openresty.init](https://github.com/openresty/openresty-packaging/blob/master/rpm/SOURCES/openresty.init#L5) as the following:

```bash
#
# chkconfig:   - 85 15
# description: OpenResty is a scalable web platform by extending
#              NGINX with Lua
```

some system admins will periodic update the system  and reboot the system, if we do not set run level for openresty, they think it do not meet they expectations.

So i want to get advice from your for the reason.

**Comment by agentzh** [comment]
@detailyang Mind to propose a pull request? Thanks!

**Comment by agentzh** [comment]
@detailyang Never mind. Just fixed in the git repos and the official yum repos of OpenResty :)

**Comment by detailyang** [comment]
@agentzh  i'm so sorry for  long time to reply (i 'm confused that i cannot receive the email notify from github), it's okay now:)
