### ISSUE TITLE
Finish up the deb packaging scripts for OpenResty

### ISSUE THREAD

**Issue by agentzh** [openresty/openresty-packaging#16]
@happyaron has done a lot of work on the official OpenResty deb packaging scripts in this repo:

https://github.com/happyaron/openresty-packaging

We need help on finishing his work and to make it (strictly) align up with the latest official OpenResty [RPM packages](http://openresty.org/en/rpm-packages.html). We'd like offer $500 as the reward :)

**Comment by agentzh** [comment]
We need to support both the Debian and Ubuntu distributions :)

**Comment by agentzh** [comment]
Okay, we just got a taker :)

**Comment by kapouer** [comment]
I'll have a look this week-end. By aligning i understand distributing the same packages. Do you have any other requirements ?

**Comment by dvigueras** [comment]
Excellent ! I'm looking forward to having the official Ubuntu PPA available, thanks for your work :)

**Comment by asychev** [comment]
We are looking forward too :boom:

**Comment by dvigueras** [comment]
Do we have any news about this?

**Comment by agentzh** [comment]
@dvigueras Yeah, our deb packager has been making good progress on this. Should finish soon.

**Comment by dvigueras** [comment]
@agentzh great! thanks for your work 👍

**Comment by ANPez** [comment]
Looking forward! :+1:

**Comment by dvigueras** [comment]
Great work, thanks! Finally this issue can be closed :1st_place_medal:

**Comment by agentzh** [comment]
This is already completed. OpenResty now provides official APT repositories for Ubuntu 14.04 ~ 17.10 and Debian 7.x ~ 9.x: https://openresty.org/en/linux-packages.html

Thanks @happyaron and @shell909090 for the generous contributions!
