### ISSUE TITLE
Why ignore the openresty.*\.init|service|init ? a mistake in .gitignore?

### ISSUE THREAD

**Issue by ihipop** [openresty/openresty-packaging#20]
These files are init files
why ignore them?

https://github.com/openresty/openresty-packaging/blob/e3254ea678efab524f7d4fb94a6dbfc8eaf3b4eb/deb/.gitignore#L4

![image](https://user-images.githubusercontent.com/423077/27001466-78afeab8-4dfd-11e7-9973-40742e280233.png)

**Comment by agentzh** [comment]
@ihipop Fixed. Thanks!
