### ISSUE TITLE
openresty deb package conffile is not being applied properly

### ISSUE THREAD

**Issue by dvigueras** [openresty/openresty-packaging#24]
Hi,

the content of the current `/deb/openresty/debian/conffile` is the following:

```
/etc/*
/usr/local/openresty/nginx/conf/*
```

It should protect files inside those folders from being removed after package uninstallation and protect them from being overwritten after package upgrade.

This is not happening right now. Test after installing and removing `openresty`:

```
# apt-get install openresty
....
Setting up openresty (1.11.2.5-1~xenial1) ...
Setting up openresty-resty (1.11.2.5-1~xenial1) ...
Setting up openresty-opm (1.11.2.5-1~xenial1) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
# 
```

```
# file /usr/local/openresty/nginx/conf/nginx.conf
/usr/local/openresty/nginx/conf/nginx.conf: ASCII text
```

```
# apt-get remove -y openresty
Reading package lists... Done
Building dependency tree
Reading state information... Done
...
Removing openresty-opm (1.11.2.5-1~xenial1) ...
Removing openresty-resty (1.11.2.5-1~xenial1) ...
Removing openresty (1.11.2.5-1~xenial1) ...
Processing triggers for libc-bin (2.23-0ubuntu9) ...
# 
```

```
# file /usr/local/openresty/nginx/conf/nginx.conf
/usr/local/openresty/nginx/conf/nginx.conf: cannot open `/usr/local/openresty/nginx/conf/nginx.conf' (No such file or directory)
```

This is specially dangerous when upgrading openresty as the main `nginx.conf` is overwritten without any confirmation and the current main webserver config is lost.

After unpacking and inspecting the .deb file, this is the content:

```
# cat ./DEBIAN/conffiles
/etc/init.d/openresty
```

The `/usr/local/openresty/nginx/conf/nginx.conf` path is missing from this file.

**Comment by agentzh** [comment]
@dvigueras Thanks for the report. I wonder why our own `conffiles` fails to get included. Will you investigate this issue for us? Debian packaging is always painful for me :)

**Comment by agentzh** [comment]
@dvigueras OK, I've found that we should rename `conffiles` to `PACKAGE.conffiles`. Already fixed in the following commit:

https://github.com/openresty/openresty-packaging/commit/3605535

Will push the new packages to our official APT repositories soon. Thanks!

**Comment by agentzh** [comment]
@dvigueras Already fixed in the `openresty_1.11.2.5-2` package for Ubuntu in our official APT repos. Please try it out on your side. Thanks!

**Comment by dvigueras** [comment]
@agentzh thanks, it works!

Now apt-get asks me about what to do with the main config file after upgrading the package:

```
Configuration file '/usr/local/openresty/nginx/conf/nginx.conf'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** nginx.conf (Y/I/N/O/D/Z) [default=N] ?
```

**Comment by agentzh** [comment]
Great. Thanks for the feedback.
