### ISSUE TITLE
Ubuntu 16.04 make build fail: zlib: gpg error: secret key not available

### ISSUE THREAD

**Issue by d9k** [openresty/openresty-packaging#25]
The end of the log after `make build` run:

```
dpkg-buildpackage: binary and diff upload (original source NOT included)
Now running lintian...
E: openresty-zlib source: source-contains-prebuilt-ms-help-file contrib/dotzlib/DotZLib.chm
W: openresty-zlib source: newer-standards-version 3.9.8 (current is 3.9.7)
E: openresty-zlib-dev: description-synopsis-is-duplicated
E: openresty-zlib-dev: dir-in-usr-local usr/local/openresty/
E: openresty-zlib-dev: dir-in-usr-local usr/local/openresty/zlib/
E: openresty-zlib-dev: dir-in-usr-local usr/local/openresty/zlib/include/
E: openresty-zlib-dev: file-in-usr-local usr/local/openresty/zlib/include/zconf.h
W: openresty-zlib-dev: file-in-unusual-dir usr/local/openresty/zlib/include/zconf.h
E: openresty-zlib-dev: file-in-usr-local usr/local/openresty/zlib/include/zlib.h
W: openresty-zlib-dev: file-in-unusual-dir usr/local/openresty/zlib/include/zlib.h
E: openresty-zlib-dev: dir-in-usr-local usr/local/openresty/zlib/lib/
E: openresty-zlib-dev: file-in-usr-local usr/local/openresty/zlib/lib/libz.a
W: openresty-zlib-dev: file-in-unusual-dir usr/local/openresty/zlib/lib/libz.a
E: openresty-zlib-dbgsym: description-synopsis-is-duplicated
E: openresty-zlib: embedded-library usr/local/openresty/zlib/lib/libz.so.1.2.11: zlib
W: openresty-zlib: description-synopsis-starts-with-article
E: openresty-zlib: description-synopsis-is-duplicated
E: openresty-zlib: dir-in-usr-local usr/local/openresty/
E: openresty-zlib: dir-in-usr-local usr/local/openresty/zlib/
E: openresty-zlib: dir-in-usr-local usr/local/openresty/zlib/lib/
E: openresty-zlib: file-in-usr-local usr/local/openresty/zlib/lib/libz.so
W: openresty-zlib: file-in-unusual-dir usr/local/openresty/zlib/lib/libz.so
E: openresty-zlib: file-in-usr-local usr/local/openresty/zlib/lib/libz.so.1
W: openresty-zlib: file-in-unusual-dir usr/local/openresty/zlib/lib/libz.so.1
E: openresty-zlib: file-in-usr-local usr/local/openresty/zlib/lib/libz.so.1.2.11
W: openresty-zlib: file-in-unusual-dir usr/local/openresty/zlib/lib/libz.so.1.2.11
W: openresty-zlib: postinst-has-useless-call-to-ldconfig
Finished running lintian.
Now signing changes and any dsc files...
 signfile openresty-zlib_1.2.11-3~xenial1.dsc OpenResty Admin <admin@openresty.com>
gpg: skipped "OpenResty Admin <admin@openresty.com>": secret key not available
gpg: /tmp/debsign.9ATtJBLK/openresty-zlib_1.2.11-3~xenial1.dsc: clearsign failed: secret key not available
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1295:
running debsign failed
Makefile:40: recipe for target 'zlib-build' failed
make: *** [zlib-build] Error 29
```

`Ubuntu 16.04 x64, CPU with no SSE 4.2 support

**Comment by agentzh** [comment]
@d9k You need to change the `OpenResty Admin <admin@openresty.com>`  authors in the `changelog` or `changelog.tt2` files with your own names with a GPG key. Apparently you cannot sign your own builds of the deb packages using a PGP key under our name.

Alternatively you can modify the `dpkg-buildpackage` command lines in the Makefile to avoid signing altogether. See

https://serverfault.com/questions/191785/how-can-i-properly-sign-a-package-i-modified-and-recompiled

**Comment by agentzh** [comment]
@d9k Why don't you just use our pre-built binary packages here?

https://openresty.org/en/linux-packages.html#ubuntu

This repo is mainly for the official OpenResty team instead of for general public use.

**Comment by d9k** [comment]
thx, @agentzh, using pre-built binary packages was the first thing I tried.
I got "trap invalid opcode" error.
After googling I realised that's because CPU in my computer doesn't support SSE 4.2 instructions.

So I rebuilt openresty from sources and it runs perfectly but I'm missing some debian integration features (like configs at `/etc/opernresty` and `systemctl` integration).

**Comment by d9k** [comment]
@agentzh, how can I edit rules files to disable signing and related checks?

**Comment by agentzh** [comment]
@d9k I think I already told you how to:

https://github.com/openresty/openresty-packaging/issues/25#issuecomment-331040347

**Comment by agentzh** [comment]
@d9k BTW, use of OpenResty on an Intel CPU without SSE 4.2 support has security vulnerabilities and is strongly discouraged.

**Comment by d9k** [comment]
@agentzh, My AMD Phenom II X4 965 (2013) CPU supports this:

` fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdts
cp lm 3dnowext 3dnow constant_tsc rep_good nopl nonstop_tsc extd_apicid pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignss
e 3dnowprefetch osvw ibs skinit wdt nodeid_msr hw_pstate vmmcall npt lbrv svm_lock nrip_save`

Are there flags I can use instead of `-msse4.2` flag?

**Comment by agentzh** [comment]
@d9k Not really. The issue is for doing fast crc32 hashing in LuaJIT's string hash function. We need the CRC instruction of the SSE 4.2 instruction set for this. Not sure if we have a good enough alternative for AMD chips though.

**Comment by agentzh** [comment]
@d9k Disabling the SSE 4.2 instruction just means that the hash collision hit might be a lot worse. Not a too big deal though.

**Comment by d9k** [comment]
> Alternatively you can modify the dpkg-buildpackage command lines in the Makefile to avoid signing altogether. See https://serverfault.com/questions/191785/how-can-i-properly-sign-a-package-i-modified-and-recompiled

Where exactly should I write `-uc -us` dpkg-buildpackage flags (for example in `deb/openresty-zlib/Makefile`) to ignore signing problems?

**Comment by agentzh** [comment]
@d9k Seems like you don't even need to change anything. Just run the `make` command in the `deb/` directory like this:

```bash
cd deb/
make OPTS='-uc -us' openresty-build
```

The Makefile there already supports the `OPTS` make variable for tuning the debuild command lines:

https://github.com/openresty/openresty-packaging/blob/master/deb/Makefile

**Comment by d9k** [comment]
@agentzh, many thanks!

trying 
```
cd deb
make OPTS='-uc -us' build
```
, the end of log:

```
E: openresty-pcre: dir-in-usr-local usr/local/openresty/
E: openresty-pcre: dir-in-usr-local usr/local/openresty/pcre/
E: openresty-pcre: dir-in-usr-local usr/local/openresty/pcre/lib/
E: openresty-pcre: file-in-usr-local usr/local/openresty/pcre/lib/libpcre.so
W: openresty-pcre: file-in-unusual-dir usr/local/openresty/pcre/lib/libpcre.so
E: openresty-pcre: file-in-usr-local usr/local/openresty/pcre/lib/libpcre.so.1
W: openresty-pcre: file-in-unusual-dir usr/local/openresty/pcre/lib/libpcre.so.1
E: openresty-pcre: file-in-usr-local usr/local/openresty/pcre/lib/libpcre.so.1.2.8
W: openresty-pcre: file-in-unusual-dir usr/local/openresty/pcre/lib/libpcre.so.1.2.8
E: openresty-pcre: file-in-usr-local usr/local/openresty/pcre/lib/libpcreposix.so
W: openresty-pcre: file-in-unusual-dir usr/local/openresty/pcre/lib/libpcreposix.so
E: openresty-pcre: file-in-usr-local usr/local/openresty/pcre/lib/libpcreposix.so.0
W: openresty-pcre: file-in-unusual-dir usr/local/openresty/pcre/lib/libpcreposix.so.0
E: openresty-pcre: file-in-usr-local usr/local/openresty/pcre/lib/libpcreposix.so.0.0.4
W: openresty-pcre: file-in-unusual-dir usr/local/openresty/pcre/lib/libpcreposix.so.0.0.4
W: openresty-pcre: postinst-has-useless-call-to-ldconfig
Finished running lintian.
#for f in openresty-pcre*.deb; do debsigs --sign=origin -K D5EDEB74 $f || exit 1; done
if [ -f ./upload ]; then ./upload || exit 1; fi
sudo apt-get -y -qq install openresty-zlib-dev
E: Unable to locate package openresty-zlib-dev
Makefile:116: recipe for target 'openssl-clean' failed
make: *** [openssl-clean] Error 100
```

I don't understand what I need to do to eliminate errors.

```
% find | grep "\.deb$"
./deb/openresty-pcre-dbgsym_8.40-1~xenial1_amd64.deb
./deb/openresty-pcre-dev_8.40-1~xenial1_amd64.deb
./deb/openresty-pcre_8.40-1~xenial1_amd64.deb
```

**Comment by agentzh** [comment]
@d9k You can just use the `openresty-zlib-dev` package (and also `openresty-openssl-dev` and `openresty-pcre-dev`) from the official apt repos of openresty. You only need to build the `openresty` package yourself (or the `openresty-debug` or `openresty-valgrind` packages).

**Comment by d9k** [comment]
@agentzh,

```
% cd deb/
% make OPTS='-uc -us' openresty-build
% find | grep "\.deb$"                                      
./openresty-opm_1.11.2.5-2~xenial1_amd64.deb
./openresty-resty_1.11.2.5-2~xenial1_all.deb
./openresty_1.11.2.5-2~xenial1_amd64.deb
./openresty-restydoc_1.11.2.5-2~xenial1_amd64.deb
./openresty-dbgsym_1.11.2.5-2~xenial1_amd64.deb
% sudo dpkg -i ./openresty_1.11.2.5-2\~xenial1_amd64.deb
. . . . .
dpkg: error processing package openresty (--install):
 subprocess installed post-installation script returned error exit status 1
% journal -xe
. . . . .
Sep 25 01:56:10 phenomIIX4 openresty[9948]: nginx: [emerg] open() "/usr/local/openresty/nginx/conf/nginx.conf" failed (2: No such file or directory)
Sep 25 01:56:10 phenomIIX4 openresty[9948]: nginx: configuration file /usr/local/openresty/nginx/conf/nginx.conf test failed
Sep 25 01:56:10 phenomIIX4 systemd[1]: openresty.service: Control process exited, code=exited status=1
Sep 25 01:56:10 phenomIIX4 systemd[1]: Failed to start A dynamic web platform based on Nginx and LuaJIT
```

**Comment by agentzh** [comment]
Before you install the openresty package you need to make sure there is nothing listening on your local 80 port. And your package might be incomplete. We never ran into such things ourselves.
