### ISSUE TITLE
openresty-zlib undefined symbol luaopen_libz

### ISSUE THREAD

**Issue by lloydhazlett** [openresty/openresty-packaging#30]
Thanks for making the debian packages available, much easier than having to maintain my own!

I'm testing on ubuntu 18.04 and everything is working for me except the packaged zlib from openresty-zlib. Trying to use it results in the error:

```
/usr/local/openresty/zlib/lib/libz.so.1: undefined symbol: luaopen_zlib
stack traceback:
coroutine 0:
	[C]: in function 'require'
	content_by_lua(test:56):2: in function <content_by_lua(test:56):1>
```

Not sure if I'm missing something or if there is a problem with the package itself.

Installed packages:

```
openresty-openssl 1.1.0h-2~bionic1   amd64
openresty-opm     1.13.6.2-1~bionic1 amd64
openresty-pcre    8.42-1~bionic1     amd64
openresty-resty   1.13.6.2-1~bionic1 all
openresty-zlib    1.2.11-3~bionic1   amd64
```

Test nginx configuration:

```
lua_package_cpath ';;/usr/local/openresty/zlib/lib/libz.so;';
server {
...
    location = /lua-zlib {
        default_type 'text/plain';
        content_by_lua_block {
            local zlib = require "libz"
            local inflate = zlib.inflate()
            content = inflate('\x1f\x8b\x08\x00Z\xfe\xbb[\x00\x03\x0b\xc9\xc8,V(.)\xca\xccKW\xc8H,VHJM\xcdSHIM\xce\xcf-(J-.NM\xd1\xe3\x02\x00\xe4[\xa2S#\x00\x00\x00')
            ngx.say(content)
        }
    }
}
```

A successful test should output the string "This string has been decompressed.".

I did note that the official ubuntu [lua-zlib](https://packages.ubuntu.com/bionic/amd64/lua-zlib/filelist) package (which I was using previously) uses the name zlib.so, rather than libz.so. I'm not sure if I should be using require "zlib" or require "libz", but they both cause the exact same error regardless.

Finally, I also understand the lua_package_cpath addition is required for the openresty-zlib module to even be found, which might be helpful to note on the [deb-packages](https://openresty.org/en/deb-packages.html) page in the openresty-zlib section. Initially I expected the module to "just work" once installed with the package, but understand why that might be difficult to achieve and that the manual path adjustment is therefore required.

Appreciate any assistance.

**Comment by agentzh** [comment]
@lloydhazlett Seems like you are trying to load the pure C library `libz.so` as a Lua C module. It won't work. "zlib.so" is the right Lua C module file for your lua-zlib library, not "libz".

**Comment by lloydhazlett** [comment]
> "zlib.so" is the right Lua C module file for your lua-zlib library, not "libz".

Thanks, but this is perhaps what was confusing me - I can't find a zlib.so file installed from any of the packages I listed? Neither of the following commands list anything:

`find /usr/local/openresty -name 'zlib.so'`
`dpkg -L openresty-openssl openresty-opm openresty-pcre openresty-resty openresty-zlib  | grep zlib.so`

It's not clear to me where I'm supposed to be installing zlib.so from.

**Comment by agentzh** [comment]
@lloydhazlett OpenResty does not ship with lua-zlib. You need to install it by yourself to OpenResty's /usr/local/openresty/lualib/site/ directory.

**Comment by lloydhazlett** [comment]
For reference, I needed to install a [lua-zlib](https://github.com/hamishforbes/lua-ffi-zlib) package, which I understand we may want to do with openresty's opkg command `opm get hamishforbes/lua-ffi-zlib`.

This installs `/usr/local/openresty/site/lualib/ffi-zlib.lua`, which we can then use as `require "ffi-zlib"`. However, libz.so then can't be loaded and we're back to an error that looks very similar to the first error I encountered:

```
runtime error: /usr/local/openresty/site/lualib/ffi-zlib.lua:98: libz.so: cannot open shared object file: No such file or directory
```

That is because the [ffi load call](https://github.com/hamishforbes/lua-ffi-zlib/blob/master/lib/ffi-zlib.lua#L98) uses the default system search path for dynamic libraries and not lua_package_cpath. The openresty zlib library path needs to be added to LD_LIBRARY_PATH, which I did by adding the line `Environment=LD_LIBRARY_PATH=/usr/local/openresty/zlib/lib:$LD_LIBRARY_PATH` to my systemd service unit based on the [package version](https://github.com/openresty/openresty-packaging/blob/master/deb/openresty/debian/openresty.service).

Finally, for the sake of my original example, note the type signature of inflate() in lua-ffi-zlib is different so that also had to be updated.

Thanks again for your help @agentzh.

**Comment by xemose** [comment]
> That is because the [ffi load call](https://github.com/hamishforbes/lua-ffi-zlib/blob/master/lib/ffi-zlib.lua#L98) uses the default system search path for dynamic libraries and not lua_package_cpath. The openresty-zlib library path needs to be added to LD_LIBRARY_PATH, which I did by adding the line `Environment=LD_LIBRARY_PATH=/usr/local/openresty/zlib/lib:$LD_LIBRARY_PATH` to my systemd service unit based on the [package version](https://github.com/openresty/openresty-packaging/blob/master/deb/openresty/debian/openresty.service)..

I've added the Environment line to my systemd service unit but am getting the same errors. 

Can you elaborate on what you did other than that?
