### ISSUE TITLE
TLS 1.3 final spec is implemented in OpenSSL 1.1.1+ only

### ISSUE THREAD

**Issue by arcivanov** [openresty/openresty-packaging#31]
Please upgrade to 1.1.1+ of OpenSSL.

**Comment by arcivanov** [comment]
@agentzh

**Comment by agentzh** [comment]
@arcivanov We need to port our openssl patches to openssl 1.1.1 first. Before that, we cannot upgrade since it will break existing features like `ssl_certificate_by_lua*`. We are still working on it. @spacewander

**Comment by arcivanov** [comment]
@agentzh is there a test suite?

**Comment by arcivanov** [comment]
@agentzh nevermind, found them :)

**Comment by thibaultcha** [comment]
Patches have been ported to OpenSSL 1.1.1 now: https://openresty.org/en/openssl-patches.html
