### ISSUE TITLE
PIDFile is no more required in openresty.service

### ISSUE THREAD

**Issue by TopNiz** [openresty/openresty-packaging#39]
Hi,
I've ran through an issue installing openresty using pre-built packages on ubuntu bionic. During install, it starts the service and waits for it to stop which leads to a timeout. The status of the service shows this error:
```
openresty.service - full-fledged web platform
   Loaded: loaded (/lib/systemd/system/openresty.service; enabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Wed 2020-03-25 01:05:52 UTC; 30s ago

mars 25 01:04:22 Codimeo-fra1-01 systemd[1]: Starting full-fledged web platform...
mars 25 01:04:22 Codimeo-fra1-01 systemd[1]: openresty.service: Can't open PID file /usr/local/openresty/nginx/logs/nginx.pid (yet?) after start: No su
mars 25 01:05:52 Codimeo-fra1-01 systemd[1]: openresty.service: Start operation timed out. Terminating.
mars 25 01:05:52 Codimeo-fra1-01 systemd[1]: openresty.service: Killing process 28387 (nginx) with signal SIGKILL.
mars 25 01:05:52 Codimeo-fra1-01 systemd[1]: openresty.service: Killing process 28390 (nginx) with signal SIGKILL.
mars 25 01:05:52 Codimeo-fra1-01 systemd[1]: openresty.service: Failed with result 'timeout'.
mars 25 01:05:52 Codimeo-fra1-01 systemd[1]: Failed to start full-fledged web `platform.
```
After many trials, the Nginx removes it's own pid file, which is ```/run/openresty.pid``` according to the default nginx.conf of openresty.
So it is not needed to mention it in the service definition file.

**Comment by agentzh** [comment]
@TopNiz Interesting. What version of the pre-built OpenResty package are you using? Is it 1.15.8.3?

**Comment by TopNiz** [comment]
Yes, the latest
```
$ openresty -v
nginx version: openresty/1.15.8.3
```

**Comment by agentzh** [comment]
Thanks. We'll look into this.

**Comment by spacewander** [comment]
@TopNiz 
Can't reproduce the issue in my side. Both 1.15.8.3 and Ubuntu 18.04.
Can you reproduce the behavior?

BTW, the pid file installed from pre-built package is still `/usr/local/openresty/nginx/logs/nginx.pid`.

**Comment by rainingmaster** [comment]
`PIDFile=/usr/local/openresty/nginx/logs/nginx.pid` should be come from [here](https://github.com/openresty/openresty-packaging/blob/master/deb/openresty/debian/openresty.service) if you use official repo,  maybe you have installed you openresty from other repo? 

Could you share your apt repo?  or you have installed it by other way?

**Comment by TopNiz** [comment]
@rainingmaster 
Here is my apt repo (from my ```/etc/apt/sources.list```):
```
deb http://openresty.org/package/ubuntu bionic main
```
@spacewander 
Here are my reproduction steps:

- ```$ sudo apt remove openresty```
- I verify that ```openresty.service``` is removed from ```/lib/systemd/system```
- ```$ sudo apt install openresty```
-  While configuring the package, the apt process hangs, wait and then crashs showing the following:
```
Job for openresty.service failed because a timeout was exceeded.
See "systemctl status openresty.service" and "journalctl -xe" for details.
invoke-rc.d: initscript openresty, action "start" failed.
● openresty.service - full-fledged web platform
   Loaded: loaded (/lib/systemd/system/openresty.service; enabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Thu 2020-03-26 16:07:05 UTC; 18ms ago
  Process: 8603 ExecStart=/usr/local/openresty/nginx/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
  Process: 8590 ExecStartPre=/usr/local/openresty/nginx/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
 Main PID: 1438 (code=exited, status=0/SUCCESS)

mars 26 16:05:35 Codimeo-fra1-01 systemd[1]: Starting full-fledged web platform...
mars 26 16:05:35 Codimeo-fra1-01 systemd[1]: openresty.service: Can't open PID file /usr/local/openresty/nginx/logs/nginx.pid (yet?) after start: No such file or directory
mars 26 16:07:05 Codimeo-fra1-01 systemd[1]: openresty.service: Start operation timed out. Terminating.
mars 26 16:07:05 Codimeo-fra1-01 systemd[1]: openresty.service: Killing process 8606 (nginx) with signal SIGKILL.
mars 26 16:07:05 Codimeo-fra1-01 systemd[1]: openresty.service: Killing process 8609 (nginx) with signal SIGKILL.
mars 26 16:07:05 Codimeo-fra1-01 systemd[1]: openresty.service: Failed with result 'timeout'.
mars 26 16:07:05 Codimeo-fra1-01 systemd[1]: Failed to start full-fledged web platform.
```
- The apt install stops and exits

I retry to start the service manually: 

- ```$ sudo service openresty status```:
```
openresty.service - full-fledged web platform
   Loaded: loaded (/lib/systemd/system/openresty.service; enabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Thu 2020-03-26 16:07:05 UTC; 2min 46s ago
 Main PID: 1438 (code=exited, status=0/SUCCESS)

mars 26 16:05:35 Codimeo-fra1-01 systemd[1]: Starting full-fledged web platform...
mars 26 16:05:35 Codimeo-fra1-01 systemd[1]: openresty.service: Can't open PID file /usr/local/openresty/nginx/logs/nginx.pid (yet?) after start: No su
mars 26 16:07:05 Codimeo-fra1-01 systemd[1]: openresty.service: Start operation timed out. Terminating.
mars 26 16:07:05 Codimeo-fra1-01 systemd[1]: openresty.service: Killing process 8606 (nginx) with signal SIGKILL.
mars 26 16:07:05 Codimeo-fra1-01 systemd[1]: openresty.service: Killing process 8609 (nginx) with signal SIGKILL.
mars 26 16:07:05 Codimeo-fra1-01 systemd[1]: openresty.service: Failed with result 'timeout'.
mars 26 16:07:05 Codimeo-fra1-01 systemd[1]: Failed to start full-fledged web platform.
```
- ```$ sudo service openresty start```:
After some delay (around 3 min...)
```
Job for openresty.service failed because a timeout was exceeded.
See "systemctl status openresty.service" and "journalctl -xe" for details.
```

After all this, to make it work, I edit the ```/lib/systemd/system/openresty.service``` as follow:
```
[Unit]
Description=full-fledged web platform
After=network.target

[Service]
Type=forking
#PIDFile=/usr/local/openresty/nginx/logs/nginx.pid
ExecStartPre=/usr/local/openresty/nginx/sbin/nginx -t -q -g 'daemon on; master_process on;'
ExecStart=/usr/local/openresty/nginx/sbin/nginx -g 'daemon on; master_process on;'
ExecReload=/usr/local/openresty/nginx/sbin/nginx -g 'daemon on; master_process on;' -s reload
#ExecStop=-/sbin/start-stop-daemon --quiet --stop --retry QUIT/5 --pidfile /usr/local/openresty/nginx/logs/nginx.pid
ExecStop=-/sbin/start-stop-daemon --quiet --stop --retry QUIT/5 
TimeoutStopSec=5
KillMode=mixed

[Install]
WantedBy=multi-user.target
```

And as you see, the mentioned PIDFile is exactly ```PIDFile=/usr/local/openresty/nginx/logs/nginx.pid```.

I save the file and start again the openresty service: success!

- ```$ sudo systemctl daemon-reload```
- ```$ sudo service openresty stop```
- ```$ sudo service openresty start```
- ```$ sudo service openresty status```
```
openresty.service - full-fledged web platform
   Loaded: loaded (/lib/systemd/system/openresty.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-03-26 16:19:56 UTC; 1min 16s ago
  Process: 11525 ExecStart=/usr/local/openresty/nginx/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
  Process: 11519 ExecStartPre=/usr/local/openresty/nginx/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
 Main PID: 11529 (nginx)
    Tasks: 2 (limit: 2318)
   CGroup: /system.slice/openresty.service
           ├─11529 nginx: master process /usr/local/openresty/nginx/sbin/nginx -g daemon on; master_process on;
           └─11532 nginx: worker process

mars 26 16:19:56 Codimeo-fra1-01 systemd[1]: Starting full-fledged web platform...
mars 26 16:19:56 Codimeo-fra1-01 systemd[1]: Started full-fledged web platform.
```

N.B: I've stopped an existing other Nginx service to test alone Openresty (But, normally, I manage to use OpenResty on port 8080).

**Comment by thibaultcha** [comment]
>  which is `/run/openresty.pid` according to the default nginx.conf of openresty.

Where is this default config you speak of? Nowhere do I see any `nginx.conf` specifying `/run/openresty.pid`.

**Comment by TopNiz** [comment]
Just in case, the ```/run/openresty.pid```is configured in the default ```nginx.conf``` under ```/usr/local/openresty/nginx/conf/```

**Comment by rainingmaster** [comment]
@TopNiz

 I think your `nginx.conf` must be change by somebody, because the default nginx.conf will use  [log/nginx.pid](https://github.com/nginx/nginx/blob/master/conf/nginx.conf#L9) as the path of pid(although the openresty [use their own nginx repo](https://github.com/openresty/openresty/blob/master/util/mirror-tarballs#L31), but is still log/nginx.pid, I have tried in a new machine).

In fact, when install nginx, it will keep the `old nginx.conf`, so when you run `service openresty start`, if system check the [PIDFile](https://www.freedesktop.org/software/systemd/man/systemd.service.html#PIDFile=), it will cannot found.

However, in my test, my system will not check the PIDFile and run success, maybe later I can have more test and find why.

**Comment by TopNiz** [comment]
Thanks!
I've proceeded with a total remove of Openresty (```sudo apt-get remove --purge openresty```). and then, I reinstalled it again, after stopping my main Nginx service. It worked. Everything worked like a charm.
I'll close the ticket.
