### ISSUE TITLE
Possible to add repository for Debian Bullseye(11)?

### ISSUE THREAD

**Issue by holishing** [openresty/openresty-packaging#56]
It seems that we can successfully install openresty and its custom depedencies (e.g. zlib, openssl) for buster(10) in bullseye(11) without apparent problem.  Although Bullseye is still in testing status, but its most of its package (kernel, libc, gcc...) is [frozen](https://release.debian.org/bullseye/freeze_policy.html) around 3/12.  Maybe it's better to test its capability earlier, also benefits users who want to help to test.  Thanks!

**Comment by holishing** [comment]
Any News?  Debian Bullseye is releasing in Aug. 14th.
https://wiki.debian.org/DebianBullseye

**Comment by xiaocang** [comment]
Hi @holishing, thanks for the reminder that we can usually provide pre-compiled binary packages after the official release

**Comment by holishing** [comment]
Just a reminder that Debian Bullseye has been released for a week.  It would be nice if there's pre-compiled binary packages for that distro.  Thanks! :)

**Comment by xiaocang** [comment]
Hi @holishing, we have built the package for debian 11
