### ISSUE TITLE
Missing Openresty 1.19.9.1-1~bionic1_amd64.deb package

### ISSUE THREAD

**Issue by sanjmohan** [openresty/openresty-packaging#67]
I've seen that v. 1.19.9.1 has been officially released, but I don't see the `1.19.9.1-1~bionic1_amd64.deb`  Bionic builds of openresty packages at https://openresty.org/package/ubuntu/pool/main/o/openresty/.

Are these builds planned / in progress? Or am I missing something or looking in the wrong place?

**Comment by agentzh** [comment]
@sanjmohan Thanks for the report! The upload script indeed missed ubuntu 18.04. Already fixed. Will you check it out again? Thanks!

**Comment by sanjmohan** [comment]
Looks good, thank you!
