### ISSUE TITLE
required packages for building the rpm package do not exist

### ISSUE THREAD

**Issue by abualy** [openresty/openresty-packaging#7]
hi,

## Context

the dependencies in  each .spec file do not work:

```shell
BuildRequires:  gcc, make, perl, systemtap-sdt-devel
BuildRequires:  openresty-zlib-devel >= 1.2.8
BuildRequires:  openresty-openssl-debug-devel >= 1.0.2h-6
BuildRequires:  openresty-pcre-devel >= 8.39
Requires:       openresty-zlib >= 1.2.8
Requires:       openresty-openssl-debug >= 1.0.2h-6
Requires:       openresty-pcre >= 8.39
```
## Expected Behavior

to install these packages without any error

## Actual Behavior

`
error: Failed build dependencies:
        openresty-zlib-devel >= 1.2.8 is needed by openresty-debug-1.11.2.1-3.el7.centos.x86_64
        openresty-openssl-debug-devel >= 1.0.2h-6 is needed by openresty-debug-1.11.2.1-3.el7.centos.x86_64
        openresty-pcre-devel >= 8.39 is needed by openresty-debug-1.11.2.1-3.el7.centos.x86_64
`

## Possible Fix

do you mean:
```shell
BuildRequires:  gcc, make, perl, systemtap-sdt-devel
BuildRequires:  zlib-devel >= 1.2.8
BuildRequires:  openssl-debug-devel >= 1.0.2h-6
BuildRequires:  pcre-devel >= 8.39
Requires:       zlib >= 1.2.8
Requires:       openssl-debug >= 1.0.2h-6
Requires:       pcre >= 8.39
```

## Steps to Reproduce
following default installation instructions on README.

## Context

trying to generate a rpm package for my centos environment

## My Environment
* Operating System and version: CentOS Linux 7 (Core)

**Comment by agentzh** [comment]
No, we do need our own packages for pcre, zlib, and OpenSSL to build. See http://openresty.org/en/rpm-packages.html for more details on our rpm package arrangement.

Why don't you use our official yum package repository for CentOS? It's much easier: http://openresty.org/en/linux-packages.html

BTW, the spec files should work or we cannot build our binary packages in the first place.

**Comment by abualy** [comment]
i see , my bad. 
I didn't pay attention to the repository that needs to be added, as i though it was only for installing the binaries directly.
Thank you.
