### ISSUE TITLE
openresty-openssl is still not in 1.1.1n in the repos

### ISSUE THREAD

**Issue by xavier2dc** [openresty/openresty-packaging#78]
@zhuizhuhaomeng Do you have an estimation when new packages lands in e.g. https://openresty.org/package/debian/pool/openresty/o/openresty-openssl111/ ?

_Originally posted by @chrko in https://github.com/openresty/openresty-packaging/issues/76#issuecomment-1072402873_

As @chrko mentioned, the packages for openresty-openssl have not been updated, making docker-openresty use an outdated version of OpenSSL. This in turn impacts e.g., jc21/nginx-proxy-manager. New packages based on OpenSSL 1.1.1n should be made available ASAP please.

**Comment by zhuizhuhaomeng** [comment]
maybe one or two days

**Comment by xavier2dc** [comment]
Seems like it's been updated now.

**Comment by tobybellwood** [comment]
I can see they have been updated for the debian/ubuntu packages - but any timeline for the alpine ones being published?
https://openresty.org/package/alpine/v3.14/main/x86_64/

**Comment by neomantra** [comment]
As noted in the [docker-openresty](https://github.com/openresty/docker-openresty/issues/199) ticket, while the new `amd64`  Linux packages are available, it seems the updated `arm64` and Alpine builds are not available yet?  

|  *uploaded*  | *dist* | *arch* |*pkg repo link* | 
| :--: | :--: | :--: |:--- |
|   | alpine | amd64 |https://openresty.org/package/alpine/v3.14/main/x86_64/ |
| *X* | debian | amd64 |https://openresty.org/package/debian/pool/openresty/o/openresty-openssl111/ |
| *X* | centos | amd64 |https://openresty.org/package/centos/8/x86_64/ |
| *X* | fedora | amd64 |https://openresty.org/package/fedora/34/x86_64/ |
|  | alpine | arm64 |https://openresty.org/package/alpine/v3.14/main/aarch64/ |
|  | debian | arm64 |https://openresty.org/package/arm64/debian/pool/openresty/o/openresty-openssl111/ |
|  | fedora | arm64 |https://openresty.org/package/fedora/34/aarch64/ |
|  | centos | arm64 |https://openresty.org/package/centos/8/aarch64/ |
