### ISSUE TITLE
openresty-openssl 1.1.1n  is still not published in the Alpine (and arm64) repos

### ISSUE THREAD

**Issue by tobybellwood** [openresty/openresty-packaging#80]
I (and also @neomantra) commented in https://github.com/openresty/openresty-packaging/issues/78#issuecomment-1074881663 - but unfortunately only after it was closed, so it may not have crossed the correct people's radars.

I can see the code has been pushed for the Alpine and arm64 repos, but the packages are still not available to download, and I really don't want to have to go down building and installing them myself if I can avoid it! Is there anything we can do to expedite their CI/publishing?

**Comment by cppcoffee** [comment]
Thanks for reporting, we are packing these two packages, please try again later.

**Comment by cppcoffee** [comment]
Hi @tobybellwood , the Alpine and arm64 we have packed, please try again.

**Comment by tobybellwood** [comment]
Thanks @cppcoffee I can see the Alpine x86_64 ones, but no arm64 for Alpine, only debian/fedora/centos?

**Comment by tobybellwood** [comment]
Closing - addressed now
